# Default instance types
bastion_instance_type: t2.medium
tower_instance_type: t2.xlarge
s4hana_instance_type: m5.8xlarge
hana_instance_type: r4.2xlarge


sap_instance_image: RHEL84GOLD
non_sap_instance_image: RHEL84GOLD

# If you'd like to use a different instance image, use the overrides below
bastion_instance_image: "{{ non_sap_instance_image }}"
tower_instance_image: "{{ non_sap_instance_image }}"
s4hana_instance_image: "{{ sap_instance_image }}"
hana_instance_image: "{{ sap_instance_image }}"

ansible_user: ec2-user
remote_user: ec2-user

bastion_public_dns: "bastion.{{ subdomain_base }}."
bastion_public_dns_chomped: "bastion.{{ subdomain_base }}"
tower_public_dns: "tower.{{ subdomain_base }}."
tower_public_dns_chomped: "tower.{{ subdomain_base }}"

aws_public_subnet_cidr: "192.168.0.0/24"

cloudformation_retries: 2

rootfs_size_bastion: 50
rootfs_size_tower: 100
rootfs_size_s4hana: 100
rootfs_size_hana: 100

security_groups:
  - name: WebSG
    rules:
      - name: HTTPPorts
        description: "HTTP Public"
        from_port: 80
        to_port: 80
        protocol: tcp
        cidr: "0.0.0.0/0"
        rule_type: Ingress

      - name: HTTPSPorts
        description: "HTTP Public"
        from_port: 443
        to_port: 443
        protocol: tcp
        cidr: "0.0.0.0/0"
        rule_type: Ingress

  - name: HostSG
    rules:
      - name: FromHostSG
        description: "Allow everything from HostSG nodes"
        from_port: 0
        to_port: 65535
        protocol: -1
        from_group: HostSG
        rule_type: Ingress


ansible_hana1_hostname: "hana1"
ansible_hana1_fqdn_hostname: "hana1.{{ guid }}.internal"
ansible_hana2_hostname: "hana2"
ansible_hana2_fqdn_hostname: "hana2.{{ guid }}.internal"
ansible_hana_hostname: "hana1"
ansible_s4hana_hostname: "s4hana"
bastion_hostname: "bastion.{{ guid }}.internal"
deployment_db_host: "hana1.{{ guid }}.internal"
